//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AocTM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AocTM_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_REPORT                      129
#define IDD_GROUPING                    131
#define IDD_PLAYERINPUT                 132
#define IDD_STATDLG                     135
#define IDR_MAINPOPMENU                 136
#define IDD_FEE                         137
#define IDD_DIALOG1                     139
#define IDD_GRAPH                       139
#define IDR_REPORTPOPMENU               140
#define IDD_FEE_IN                      141
#define IDD_CONFIG_CHARGE               142
#define IDD_CONFIG_PLAYER               143
#define IDR_ACCELERATOR1                145
#define IDD_GAMEINFO                    146
#define IDR_RECPOPMENU                  148
#define IDC_ReportList                  1000
#define IDC_PLAYERS                     1002
#define IDC_SELECTED                    1003
#define IDC_GROUP1                      1004
#define IDC_GROUP2                      1005
#define IDC_TOTAL1                      1006
#define IDC_MSG                         1006
#define IDC_TOTAL2                      1007
#define IDC_RESET                       1009
#define IDC_BUTTON2                     1010
#define IDC_NEW                         1010
#define IDC_INPUT                       1010
#define IDC_CANCEL                      1010
#define IDC_IDD_PLAYER_DELETE           1010
#define IDC_PLAYER_DELETE               1010
#define IDC_REC_DISMISS                 1010
#define IDC_EDITNAME                    1011
#define IDC_EDITRATING                  1012
#define IDC_BUTTON1                     1014
#define IDC_KEEP                        1014
#define IDC_INIT                        1014
#define IDC_SAVE                        1014
#define IDC_DELETE                      1014
#define IDC_PLAYER_ADD                  1014
#define IDC_REC_DELETE                  1014
#define IDC_BUTTON_ZOOM                 1014
#define IDC_SPINRATING                  1015
#define IDC_BUTTON_Measure              1015
#define IDC_LIST1                       1016
#define IDC_BUTTON_MARK                 1016
#define IDC_DATABASEDUE                 1017
#define IDC_DATABASE                    1017
#define IDC_TITLE                       1017
#define IDC_BUTTON_Select               1017
#define IDC_LIST                        1018
#define IDC_BUTTON_Reset                1018
#define IDC_EXCHANGE                    1019
#define IDC_BUTTON_Clear                1019
#define IDC_LIST2                       1020
#define IDC_BUTTON_Measure2             1020
#define IDC_BUTTON_ClearMeasure         1020
#define IDC_FEE_MONEY                   1022
#define IDC_FEE_DATE                    1023
#define IDC_FEE_SPIN                    1024
#define IDC_FEE_LIST                    1025
#define IDC_CHARGE_DATE                 1026
#define IDC_CHARGE_MONEY                1027
#define IDC_CHARGE_MONEY_SPIN           1028
#define IDC_CHARGE_ADD                  1029
#define IDC_CHARGE_DELETE               1030
#define IDC_CHARGE_LIST                 1031
#define IDC_TAB1                        1032
#define IDC_PLAYER_LIST                 1033
#define IDC_DATETIMEPICKER1             1036
#define IDC_DATETIME_TO                 1036
#define IDC_DATETIME_FROM               1037
#define IDC_REC_LIST                    1038
#define IDC_CHATB4GAME                  1039
#define IDC_CHATINGAME                  1040
#define IDC_VERSION                     1041
#define IDC_SUMMARY                     1042
#define IDC_MONEY_IN_TOTAL              1043
#define IDC_MONEY_OUT_TOTAL             1044
#define IDC_CHECK_4v3                   1044
#define IDC_PLAYCOUNT_TOTAL             1045
#define IDC_MONEY_LEFT_TOTAL2           1046
#define IDC_MONEY_LEFT_TOTAL            1046
#define IDC_Curve_XGraph                1047
#define IDC_STATIC_Info                 1048
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_STATISTIC                    32782
#define ID_VIEWHISTORY                  32783
#define ID_GROUPING                     32784
#define ID_SELECTIONS_FEE               32785
#define ID_FEE                          32786
#define ID__RATINGCURVE                 32787
#define ID__USEDCIVS                    32788
#define ID__TECHSTAT                    32789
#define ID_CONFIG                       32792
#define ID_CONFIG_CHARGE                32793
#define ID_CONFIG_PLAYERINITIALIZE      32794
#define ID_ACCELERATOR_LOAD             32795
#define ID__SETWINNER                   32797
#define ID_SETWINNER_0                  32798
#define ID_SETWINNER_1                  32799
#define ID_SETWINNER_2                  32800
#define ID_SETWINNER_CLEAR              32801
#define ID__GROUPTHIS                   32802
#define ID__REGROUPTHIS                 32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
